default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: omer
  password: omer

development:
  <<: *default
  database: first_pro_development

test:
  <<: *default
  database: first_pro_test

